[build]
command = "npm run build:ssr"
publish = "dist/universite-chk-frontend/browser"
functions = "dist/universite-chk-frontend/server"

[dev]
command = "npm run dev:ssr"

[[redirects]]
  from = "/api/*"
  to = "https://ton-backend-spring.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
